### ISSUE TITLE
Some error in working tree 

### ISSUE THREAD

**Issue by jaskiratmokha** [dsc-gtbit/HACKTOBERFEST21-GTBIT-COMPETITIVE#20]
<img width="442" alt="error" src="https://user-images.githubusercontent.com/75515362/136990487-d34a826d-7bb1-426f-b072-f2e1f242abca.PNG">

There is some issue while cloning this repository due to which I was unable to contribute via bash so had to make a pull request via {upload files}.

**Comment by rishabh0906** [comment]
same error  invalidpath @mridul8920
