### ISSUE TITLE
2.Maximum and minimum of an array using minimum number of comparisons

### ISSUE THREAD

**Issue by mridul8920** [dsc-gtbit/HACKTOBERFEST21-GTBIT-COMPETITIVE#5]
Ques: Maximum and minimum of an array using minimum number of comparisons

Ref : https://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/

Language: C++

**Comment by simarpreetsingh-019** [comment]
okay mridul i will assign this issue to you.
