### ISSUE TITLE
Right Side Binary Tree View

### ISSUE THREAD

**Issue by Ruheej1** [dsc-gtbit/HACKTOBERFEST21-GTBIT-COMPETITIVE#96]
Question is:

Given a Binary Tree, find Right view of it. Right view of a Binary Tree is set of nodes visible when tree is viewed from right side.

I would like to add the code for it  in CPP. Please assign the issue and add the hacktoberfest lable to it, Thanks

**Comment by mridul8920** [comment]
The issue has been assigned to you
