### ISSUE TITLE
Balanced Binary Tree

### ISSUE THREAD

**Issue by Ruheej1** [dsc-gtbit/HACKTOBERFEST21-GTBIT-COMPETITIVE#97]
Ques is: 
Given a binary tree, find if it is height balanced or not. 
A tree is height balanced if difference between heights of left and right subtrees is not more than one for all nodes of tree. 

Example 1:
Input: root = [3,9,20,null,null,15,7]
Output: true

I want to add its code in CPP, please assign the issue to me and add the hacktoberfest label. Thanks :)

**Comment by mridul8920** [comment]
The issue has been assigned to you.
